//Written By Ken Yesh
//GitHub:
//
//Liablity Satement: I am not liable for anything that goes wrong use at your own risk
//
//
//Usage: As of right now you are free to use and modify 
      //this software however you please just give credit
      //where credit is due by leaving the comments above

// Warnings: Someone can drive this off a table or it can
            //glitch and drive itself off a table
//


import processing.serial.*;

// The serial port:
Serial myPort;
//Input the path to the file generated by your PHP script 
String commandLocation = "http://yoursitehere.com/path/commands.txt" ;
String[] inputFile = loadStrings(commandLocation);
void setup(){
 
// List all the available serial ports:
println(Serial.list());

// Open the port you are using at the rate you want:
myPort = new Serial(this, Serial.list()[1], 57600);
//Serial.list()[1] change number in square brackets to approprite port
//See out put from println(Serial.list())

// Send First set of commands to wake up the roomba 
//For more infot on what all the command so google irobot open interface
myPort.write(128);//Start command
myPort.write(132);//130 for roombas,
                  //131 is safe mode for Irobot Create
                  //132 is full mode for Irobot Create
myPort.write(0); 
myPort.write(145);//Specify drive input type
myPort.write(Integer.parseInt(inputFile[0])); 
myPort.write(Integer.parseInt(inputFile[1])); 
myPort.write(Integer.parseInt(inputFile[2]));
myPort.write(Integer.parseInt(inputFile[3]));

}

void draw() {
  
//Input the path to the file generated by your PHP script 
inputFile = loadStrings(commandLocation);


myPort.write(145); 
myPort.write(Integer.parseInt(inputFile[0])); 
myPort.write(Integer.parseInt(inputFile[1])); 
myPort.write(Integer.parseInt(inputFile[2]));
myPort.write(Integer.parseInt(inputFile[3]));


}
